# Generated by Django 3.2.8 on 2022-06-02 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('fullName', models.CharField(max_length=255, null=True)),
                ('mobileNo', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('dateOfBirth', models.CharField(max_length=255, null=True)),
                ('zipCode', models.CharField(max_length=255)),
                ('isActive', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('isVerified', models.BooleanField(default=False)),
                ('deviceType', models.IntegerField(choices=[(1, 'Android'), (2, 'IOS')], null=True)),
                ('genderType', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Transgender'), (4, 'Non-Binary'), (5, 'Prefer Not to Answer')], null=True)),
                ('deviceToken', models.CharField(max_length=255, null=True)),
                ('profileImage', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.FloatField(blank=True, default=0.0, null=True)),
                ('lng', models.FloatField(blank=True, default=0.0, null=True)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('isAvailable', models.BooleanField(default=False)),
                ('isApproved', models.IntegerField(choices=[(1, 'pending'), (2, 'approved'), (3, 'disapproved')], default=1)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
