# Generated by Django 3.2.8 on 2022-06-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dateOfBirth',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='genderType',
            new_name='gender',
        ),
        migrations.AddField(
            model_name='user',
            name='activityLevel',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='currentWeight',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dietaryPreferences',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='goalWeight',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='goals',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hobbies',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phoneNumberCountryCode',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='workoutPreferences',
            field=models.TextField(null=True),
        ),
    ]
