# Generated by Django 3.2.8 on 2022-05-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zipCode',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
