# Generated by Django 3.2.8 on 2022-06-05 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dietaryPreferences',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='user',
            name='workoutPreferences',
        ),
    ]
