# Generated by Django 3.2.8 on 2022-05-27 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0002_user_zipcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='licenseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licenseTypeName', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'license_types',
            },
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.CreateModel(
            name='ProviderUserLicenseDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('providerUserDocUrl', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='providerLicenseDoc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'provider_user_docs',
            },
        ),
        migrations.CreateModel(
            name='ProviderUserAdditionalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.IntegerField(default=0)),
                ('licenseName', models.CharField(blank=True, max_length=255, null=True)),
                ('licenseNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('licenseTypeId', models.ForeignKey(db_column='licenseTypeId', on_delete=django.db.models.deletion.CASCADE, related_name='licenseTypeIdData', to='auth_APIs.licensetype')),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='providerData', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'provider_user_additional_data',
            },
        ),
    ]
