# Generated by Django 3.2.8 on 2022-05-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0003_auto_20220527_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isApproved',
            field=models.IntegerField(choices=[(1, 'pending'), (2, 'approved'), (3, 'disapproved')], default=1),
        ),
    ]
