# Generated by Django 3.2.8 on 2022-06-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0004_user_isapproved'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensetype',
            name='category',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='licensetype',
            name='description',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='licensetype',
            name='requirment',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='licensetype',
            name='therapyType',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
