# Generated by Django 3.2.8 on 2022-06-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietarypreferences',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hobbies',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workoutpreferences',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
